name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - ipython
  - jupyter
  - lxml
  - requests
  - pip
  - pip: 
    - statsmodels
    - pandas-datareader
